/** Key international surnames / names per WC nation — matched against FPL `players_static`. */
export const WC_INTERNATIONAL_NAME_HINTS: Record<string, string[]> = {
  MEX: ["Ochoa", "Álvarez", "Lozano", "Jiménez", "Vega", "Montiel", "Guardado", "Herrera"],
  KOR: ["Son", "Kim", "Hwang", "Lee", "Cho", "Jung", "Paik"],
  RSA: ["Williams", "Mokoena", "Tau", "Mabusi", "Modiba"],
  CZE: ["Schick", "Souček", "Coufal", "Staněk", "Barák", "Hložek"],
  CAN: ["Davies", "David", "Buchanan", "Larin", "Eustáquio", "Miller"],
  SUI: ["Sommer", "Akanji", "Xhaka", "Shaqiri", "Embolo", "Rieder", "Kobel"],
  QAT: ["Almoez", "Afif", "Hassan", "Barsham"],
  BIH: ["Džeko", "Krunić", "Tahirović", "Demirović"],
  BRA: ["Alisson", "Marquinhos", "Casemiro", "Vinícius", "Rodrygo", "Raphinha", "Paquetá", "Bruno Guimarães", "Endrick"],
  MAR: ["Bono", "Hakimi", "Ziyech", "En-Nesyri", "Ounahi", "Amrabat", "Saïss"],
  SCO: ["McTominay", "Tierney", "Robertson", "Adams", "Gordon", "Dykes"],
  HAI: ["Pierre", "Duverger", "Lambert", "Jean"],
  USA: ["Pulisic", "McKennie", "Reyna", "Turner", "Weah", "Musah", "Balogun"],
  PAR: ["Almirón", "Santander", "Gómez", "Vallejo"],
  AUS: ["Ryan", "Goodwin", "Irvine", "Maclaren", "Boyle", "Metcalfe"],
  TUR: ["Çalhanoğlu", "Güler", "Yıldız", "Ünder", "Mert", "Demiral"],
  GER: ["Musiala", "Wirtz", "Kimmich", "Gündogan", "Havertz", "Sané", "Tah", "Raum", "Neuer"],
  ECU: ["Caicedo", "Estupiñán", "Valencia", "Plata", "Hincapié"],
  CIV: ["Zaha", "Adingra", "Haller", "Kessié", "Sangaré"],
  CUW: ["Janga", "Leerdam", "Gaari", "Martina"],
  NED: ["Van Dijk", "Gakpo", "Depay", "Simons", "Reijnders", "Frimpong", "Verbruggen"],
  JPN: ["Mitoma", "Kubo", "Minamino", "Ito", "Endo", "Suzuki", "Tomiyasu"],
  TUN: ["Skhiri", "Khazri", "Laidouni", "Msakni"],
  SWE: ["Isak", "Kulusevski", "Forsberg", "Lindelöf", "Gyökeres"],
  BEL: ["Lukaku", "De Bruyne", "Tielemans", "Doku", "Dias", "Courtois", "Castagne"],
  IRN: ["Taremi", "Azmoun", "Ghoddos", "Ezatolahi"],
  EGY: ["Salah", "Elneny", "Hegazi", "Marmoush", "Trezeguet"],
  NZL: ["Wood", "Ryan", "Boxall", "Singh"],
  ESP: ["Yamal", "Pedri", "Morata", "Rodri", "Carvajal", "Simón", "Williams", "Olmo"],
  URU: ["Valverde", "Núñez", "Araujo", "Bentancur", "Darwin", "Olivera"],
  KSA: ["Al-Dawsari", "Al-Faraj", "Al-Breik", "Al-Muwallad"],
  CPV: ["Semedo", "Monteiro", "Cabral", "Lopes"],
  FRA: ["Mbappé", "Griezmann", "Dembele", "Saliba", "Upamecano", "Maignan", "Camavinga", "Tchouaméni"],
  SEN: ["Mané", "Koulibaly", "Gueye", "Sarr", "Jackson", "Diallo"],
  NOR: ["Haaland", "Ødegaard", "Ryerson", "Nyland", "Nypan"],
  IRQ: ["Hussein", "Doski", "Fattah"],
  ARG: ["Messi", "Martinez", "Alvarez", "Lautaro", "Mac Allister", "Fernández", "Romero", "Emi Martínez"],
  AUT: ["Alaba", "Sabitzer", "Baumgartner", "Laimer", "Gregoritsch"],
  ALG: ["Mahrez", "Bennacer", "Bounedjah", "Atal"],
  JOR: ["Olwan", "Nasr", "Al-Naimat"],
  POR: ["Ronaldo", "Leão", "Bruno Fernandes", "Dias", "Costa", "Neves", "Cancelo"],
  COL: ["Díaz", "James", "Lerma", "Mina", "Sánchez"],
  UZB: ["Shomurodov", "Masharipov", "Khamdamov"],
  COD: ["Bakambu", "Mpeko", "Mbokani"],
  ENG: ["Kane", "Saka", "Bellingham", "Palmer", "Rice", "Pickford", "Foden", "Watkins", "Grealish"],
  CRO: ["Modrić", "Perišić", "Gvardiol", "Livaković", "Kovačić", "Brozović"],
  PAN: ["Godoy", "Fajardo", "Anderson"],
  GHA: ["Kudus", "Partey", "Ayew", "Amartey", "Ati-Zigi"],
};

export function nameMatchesHint(name: string, hints: string[]): boolean {
  const n = name.toLowerCase();
  return hints.some((h) => n.includes(h.toLowerCase()));
}
