/** FIFA 3-letter codes → flag emoji (ISO 3166-1 alpha-2 where applicable). */
const WC_FLAG: Record<string, string> = {
  MEX: "🇲🇽",
  KOR: "🇰🇷",
  RSA: "🇿🇦",
  CZE: "🇨🇿",
  CAN: "🇨🇦",
  SUI: "🇨🇭",
  QAT: "🇶🇦",
  BIH: "🇧🇦",
  BRA: "🇧🇷",
  MAR: "🇲🇦",
  SCO: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  HAI: "🇭🇹",
  USA: "🇺🇸",
  PAR: "🇵🇾",
  AUS: "🇦🇺",
  TUR: "🇹🇷",
  GER: "🇩🇪",
  ECU: "🇪🇨",
  CIV: "🇨🇮",
  CUW: "🇨🇼",
  NED: "🇳🇱",
  JPN: "🇯🇵",
  TUN: "🇹🇳",
  SWE: "🇸🇪",
  BEL: "🇧🇪",
  IRN: "🇮🇷",
  EGY: "🇪🇬",
  NZL: "🇳🇿",
  ESP: "🇪🇸",
  URU: "🇺🇾",
  KSA: "🇸🇦",
  CPV: "🇨🇻",
  FRA: "🇫🇷",
  SEN: "🇸🇳",
  NOR: "🇳🇴",
  IRQ: "🇮🇶",
  ARG: "🇦🇷",
  AUT: "🇦🇹",
  ALG: "🇩🇿",
  JOR: "🇯🇴",
  POR: "🇵🇹",
  COL: "🇨🇴",
  UZB: "🇺🇿",
  COD: "🇨🇩",
  ENG: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  CRO: "🇭🇷",
  PAN: "🇵🇦",
  GHA: "🇬🇭",
};

export function wcTeamFlag(code: string): string {
  return WC_FLAG[code.toUpperCase()] ?? "🏳️";
}
