/** FIFA 3-letter codes → ISO 3166-1 alpha-2 for flagcdn.com (Windows-friendly vs emoji). */
const WC_ISO2: Record<string, string> = {
  MEX: "mx",
  KOR: "kr",
  RSA: "za",
  CZE: "cz",
  CAN: "ca",
  SUI: "ch",
  QAT: "qa",
  BIH: "ba",
  BRA: "br",
  MAR: "ma",
  SCO: "gb-sct",
  HAI: "ht",
  USA: "us",
  PAR: "py",
  AUS: "au",
  TUR: "tr",
  GER: "de",
  ECU: "ec",
  CIV: "ci",
  CUW: "cw",
  NED: "nl",
  JPN: "jp",
  TUN: "tn",
  SWE: "se",
  BEL: "be",
  IRN: "ir",
  EGY: "eg",
  NZL: "nz",
  ESP: "es",
  URU: "uy",
  KSA: "sa",
  CPV: "cv",
  FRA: "fr",
  SEN: "sn",
  NOR: "no",
  IRQ: "iq",
  ARG: "ar",
  AUT: "at",
  ALG: "dz",
  JOR: "jo",
  POR: "pt",
  COL: "co",
  UZB: "uz",
  COD: "cd",
  ENG: "gb-eng",
  CRO: "hr",
  PAN: "pa",
  GHA: "gh",
};

/** Legacy emoji flags (fallback). */
const WC_FLAG: Record<string, string> = {
  MEX: "🇲🇽",
  KOR: "🇰🇷",
  RSA: "🇿🇦",
  CZE: "🇨🇿",
  CAN: "🇨🇦",
  SUI: "🇨🇭",
  QAT: "🇶🇦",
  BIH: "🇧🇦",
  BRA: "🇧🇷",
  MAR: "🇲🇦",
  SCO: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  HAI: "🇭🇹",
  USA: "🇺🇸",
  PAR: "🇵🇾",
  AUS: "🇦🇺",
  TUR: "🇹🇷",
  GER: "🇩🇪",
  ECU: "🇪🇨",
  CIV: "🇨🇮",
  CUW: "🇨🇼",
  NED: "🇳🇱",
  JPN: "🇯🇵",
  TUN: "🇹🇳",
  SWE: "🇸🇪",
  BEL: "🇧🇪",
  IRN: "🇮🇷",
  EGY: "🇪🇬",
  NZL: "🇳🇿",
  ESP: "🇪🇸",
  URU: "🇺🇾",
  KSA: "🇸🇦",
  CPV: "🇨🇻",
  FRA: "🇫🇷",
  SEN: "🇸🇳",
  NOR: "🇳🇴",
  IRQ: "🇮🇶",
  ARG: "🇦🇷",
  AUT: "🇦🇹",
  ALG: "🇩🇿",
  JOR: "🇯🇴",
  POR: "🇵🇹",
  COL: "🇨🇴",
  UZB: "🇺🇿",
  COD: "🇨🇩",
  ENG: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  CRO: "🇭🇷",
  PAN: "🇵🇦",
  GHA: "🇬🇭",
};

export function wcTeamFlagIso(code: string): string | null {
  return WC_ISO2[code.toUpperCase()] ?? null;
}

/** PNG flag URL proxied via our API (avoids CDN blocks on desktop / corporate networks). */
export function wcTeamFlagSrc(code: string, width = 24): string | null {
  const iso = wcTeamFlagIso(code);
  if (!iso) return null;
  return `/api/wc/flag?code=${encodeURIComponent(code.toUpperCase())}&w=${width}`;
}

export function wcTeamFlag(code: string): string {
  return WC_FLAG[code.toUpperCase()] ?? "🏳️";
}
